kind: Pod
apiVersion: v1
metadata:
  name: iraj-dummy-pod
spec:
  containers:
    - name: iraj-dummy-pod
      image: hedayati/toolset:latest
      imagePullPolicy: Always
      command: ["/bin/bash", "-ec", "while :; do echo '.'; sleep 5 ; done"]
      resources:
        requests:
          cpu: 1000m
          memory: 2500Mi
        limits:
          cpu: 1000m
          memory: 2500Mi
  restartPolicy: Never
