kind: Pod
apiVersion: v1
metadata:
  name: ete-perf-monitor
spec:
  containers:
    - name: ete-perf-monitor
      image: hedayati/toolset:latest
      imagePullPolicy: Always
      command: ["/bin/bash", "-ec", "while :; do echo '.'; sleep 5 ; done"]
      resources:
        requests:
          cpu: 200m
          memory: 700Mi
        limits:
          cpu: 200m
          memory: 700Mi
  restartPolicy: Never
